name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.1.0"
      - name: Check Clang++ Version
        run: |
          clang++ -v
          llvm-config --has-rtti
      - name: Run e2e test runner
        run: |
          node ./scripts/run_e2e_tests.js
