name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - name: Check PWD
        run: |
          echo $PWD
          ls
      - name: Run e2e test runner
        run: |
          node scripts/run_e2e_tests.js
